name: fiteens
description: Fiteens Mobile Application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.9.6+11

environment:
  sdk: ">=2.17.0 "

dependencies:
  build_runner: ^2.4.5
  flutter:
    sdk: flutter
   #internationalization:
  flutter_localizations:
      sdk: flutter
  intl: ^0.19.0
  provider: ^6.0.0

  #scoped_model: "^1.1.0"
  shared_preferences: ^2.0.5
  #flushbar: ^1.10.4
  #local database:
  sqflite: ^2.0.0+3
  path_provider: ^2.0.8
  #calendar day list for the calendar - view
  table_calendar: ^3.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  url_launcher: ^6.0.2
  another_flushbar: ^1.10.17
  flutter_html: ^3.0.0-alpha.2
  settings_ui: ^2.0.1
  percent_indicator: ^4.0.0
  package_info_plus: ^5.0.1
  feedback: ^3.0.0
  wakelock: ^0.6.0+1
  graphview: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  # file downloads
  dio: ^5.3.3
  cached_network_image: ^3.2.3
  core:
    git:
      url: git@github.com:Innoventum-oy/core.git
      path: core/
  hive_flutter: ^1.1.0
  flutter_settings_ui: ^3.0.0
  flutter_radar_chart: ^0.2.1
  collection: ^1.17.2
  pod_player: ^0.2.1
  html: ^0.15.4
  loading_gifs: ^0.3.0
  calendar_date_picker2: ^0.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

#if you make changes, regenerate with flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: 15303D
  image: images/logo.png

#if you make changes, regenerate with flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/logo.png"

dependency_overrides:

  #dependency updates in local package
  wakelock:
    git:
      url: https://github.com/amb-jannel/wakelock/
      path: wakelock/
  wakelock_windows:
    git:
      url: https://github.com/amb-jannel/wakelock/
      path: wakelock_windows

  core:
    path: /Users/jleinone/flutter_projects/core/core
    # local path for faster development

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  generate: true #for int
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/config/
    - images/
    - images/avatar/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
fonts:
  - family: Nunito
    fonts:
      - asset: assets/fonts/Nunito/Nunito-VariableFont_wght.ttf
      - asset: assets/fonts/Nunito/Nunito-Italic-VariableFont_wght.ttf
        style: italic

flutter_intl:
  enabled: true